### ISSUE TITLE
Question - How to set mime type per application

### ISSUE THREAD

**Issue by spuder** [opscode-cookbooks/iis#189]
Very related to https://github.com/opscode-cookbooks/iis/issues/145

How do you set a mime type at the application level (instead of the root level) ?

**Comment by EasyAsABC123** [comment]
So as I truly believe Chef believes in CD (Continuous Delivery) I don't think Application Level/Website Level are a good idea as it actually creates a Web.Config file.  This file should likely already be created and deployed via another method.

So the short answer is, this isn't currently supported.

The longer answer is, i'm not sure this is a good long term plan due to the impact on delivering a product.  However, adding support for this is rather simple since the functions are already declared in the Helper.rb library

**Comment by spuder** [comment]
I'd like to understand better. How is continuous delivery affected by having web.conf files? 

I do have some web.conf files that are managed by chef. Can mime types be specified in the web.configs ?

**Comment by EasyAsABC123** [comment]
Yes, for site specific and application specific mime types they are managed in just the standard Web.config in the respective root folder.

You can just put these mimeType and default documents in those web.config.  Because of this I don't now if chef doing this change via a recipe makes sense.

Here's my scenario:
Developer asks for site, and tells you default document
You setup recipe to setup this site and application pool, with this default document
Chef is now editing the web.config so the artifact you are deploying isn't the artifact that you want on the server.
You release version 1.1.2 of your site, the web.config will be wrong until the mimeType and default document changes run for that site (once every 30 minutes or called during your deployment).
If developer wants a new default document someone has to edit the recipe to change it.


Instead:
Developer defines mine types and default documents in their web.config and transforms or whatever they are using for different environments.
You setup the site and application pool, you are done.
Developer can change those mimetypes and default documents at their own will in source control, no knife upload and all that.

This is just my thoughts and opinion on the matter not a definitive answer.  If you can give me a use case where it is better to have chef changing the web.config then I'll accept it and write the new functionality.

**Comment by spuder** [comment]
Thanks, yes, that makes sense. Either chef should manage the entire file, or not at all.
